ERROR 2021-08-06 13:17:41,805 C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\utils\log.py (<class 'django.core.exceptions.FieldError'>, FieldError('Related Field got invalid lookup: icontains'), <traceback object at 0x000002BBAE9827C8>) Internal Server Error: /news/search/
Traceback (most recent call last):
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'PostFilter' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\defaulttags.py", line 163, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django_filters\filterset.py", line 243, in qs
    qs = self.filter_queryset(qs)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django_filters\filterset.py", line 230, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django_filters\filters.py", line 146, in filter
    qs = self.get_method(qs)(**{lookup: value})
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\db\models\sql\query.py", line 1413, in _add_q
    split_subq=split_subq, check_filterable=check_filterable,
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\db\models\sql\query.py", line 1182, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
ERROR 2021-08-06 13:17:41,809 C:\Users\79116\PycharmProjects\DjangoNews\venv\lib\site-packages\django\core\servers\basehttp.py None "GET /news/search/?time_creation=&title_post=&author=%D0%98%D0%B2%D0%B0%D0%BD HTTP/1.1" 500 435559
